# Generated by Django 2.0.4 on 2018-04-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(default='A product'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(default='dummy name', max_length=100),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_fr',
            field=models.TextField(default='Description par défaut'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_fr',
            field=models.CharField(default='Nom par défaut', max_length=100),
        ),
    ]
