# Generated by Django 2.0.4 on 2018-04-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180422_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_image',
            new_name='ProductImage',
        ),
    ]
